"""initial schema: 12 tables

Revision ID: 259b179158bd
Revises: 
Create Date: 2026-09-12 14:40:54.080456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259b179158bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('dominant_sectors', sa.String(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emission_factors',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('canonical_unit', sa.String(), nullable=False),
    sa.Column('kgco2e_per_unit', sa.Float(), nullable=False),
    sa.Column('gj_per_unit', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('applies_to', sa.JSON(), nullable=False),
    sa.Column('reduction_pct', sa.Float(), nullable=False),
    sa.Column('capex_base_inr', sa.Float(), nullable=False),
    sa.Column('saving_inr_per_tco2', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('factories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('consent_to_share', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('factory_id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('share_of_energy', sa.Float(), nullable=False),
    sa.Column('benchmark_kgco2e_per_t', sa.Float(), nullable=False),
    sa.Column('benchmark_source', sa.Text(), nullable=False),
    sa.Column('benchmark_confidence', sa.String(), nullable=False),
    sa.Column('co2e_tpy', sa.Float(), nullable=True),
    sa.Column('share_of_total', sa.Float(), nullable=True),
    sa.Column('actual_intensity', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('root_cause_text', sa.Text(), nullable=True),
    sa.Column('root_cause_rules', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbiosis_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_factory_id', sa.String(), nullable=False),
    sa.Column('recipient_factory_id', sa.String(), nullable=False),
    sa.Column('waste_tag', sa.String(), nullable=False),
    sa.Column('quantity_tpy', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('co2_avoided_tpy', sa.Float(), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['provider_factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['recipient_factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waste_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factory_id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('hazardous_waste_t', sa.Float(), nullable=False),
    sa.Column('general_process_waste_t', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('co2e_t', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emission_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('fuel_key', sa.String(), nullable=False),
    sa.Column('co2e_t', sa.Float(), nullable=False),
    sa.Column('emission_factor_kgco2e_per_unit', sa.Float(), nullable=False),
    sa.Column('emission_factor_source', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('fuel_key', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('canonical_unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('intervention_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('capex_inr', sa.Float(), nullable=False),
    sa.Column('annual_saving_inr', sa.Float(), nullable=False),
    sa.Column('co2_reduction_tpy', sa.Float(), nullable=False),
    sa.Column('payback_months', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('circularity_gain_pct', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('energy_records')
    op.drop_table('emission_records')
    op.drop_table('anomalies')
    op.drop_table('waste_records')
    op.drop_table('symbiosis_matches')
    op.drop_table('equipment')
    op.drop_table('factories')
    op.drop_table('interventions')
    op.drop_table('explanations')
    op.drop_table('emission_factors')
    op.drop_table('clusters')
    # ### end Alembic commands ###
