"""add cost savings to symbiosis_matches

Revision ID: 577ebc531e98
Revises: 710805dc8246
Create Date: 2026-09-12 17:19:59.960653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577ebc531e98'
down_revision: Union[str, Sequence[str], None] = '710805dc8246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbiosis_matches', sa.Column('provider_saving_inr', sa.Float(), nullable=False))
    op.add_column('symbiosis_matches', sa.Column('recipient_saving_inr', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbiosis_matches', 'recipient_saving_inr')
    op.drop_column('symbiosis_matches', 'provider_saving_inr')
    # ### end Alembic commands ###
