"""add score breakdown to symbiosis_matches

Revision ID: 710805dc8246
Revises: c13e8e55e64b
Create Date: 2026-09-12 17:10:39.948213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710805dc8246'
down_revision: Union[str, Sequence[str], None] = 'c13e8e55e64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbiosis_matches', sa.Column('quantity_fit_score', sa.Float(), nullable=False))
    op.add_column('symbiosis_matches', sa.Column('proximity_score', sa.Float(), nullable=False))
    op.add_column('symbiosis_matches', sa.Column('overall_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbiosis_matches', 'overall_score')
    op.drop_column('symbiosis_matches', 'proximity_score')
    op.drop_column('symbiosis_matches', 'quantity_fit_score')
    # ### end Alembic commands ###
