"""add factory.output_tonnes_per_year

Revision ID: 7768ee4c1370
Revises: 259b179158bd
Create Date: 2026-09-12 14:53:29.001620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7768ee4c1370'
down_revision: Union[str, Sequence[str], None] = '259b179158bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('output_tonnes_per_year', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'output_tonnes_per_year')
    # ### end Alembic commands ###
