"""add waste_streams and accepted_inputs tables

Revision ID: c13e8e55e64b
Revises: 7768ee4c1370
Create Date: 2026-09-12 17:07:18.138175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13e8e55e64b'
down_revision: Union[str, Sequence[str], None] = '7768ee4c1370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accepted_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factory_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('max_tpy', sa.Float(), nullable=False),
    sa.Column('virgin_cost_inr_per_t', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waste_streams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factory_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('tpy', sa.Float(), nullable=False),
    sa.Column('disposal_cost_inr_per_t', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_streams')
    op.drop_table('accepted_inputs')
    # ### end Alembic commands ###
